mybatis:
  config-location: classpath:mybatis/mybatisConfig.xml #  mybatis主配置文件所在路径
  #  type-aliases-package: cn.lizheng.study.mybatis.pojo   #  定义所有操作类的别名所在包
  mapper-locations:                                     # 定义所有mapper文件
    - classpath*:mybatis/mappers/*.xml


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #  配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver    #  配置mysql的驱动程序类
    url: jdbc:mysql://127.0.0.1:3306/myblog?useUnicode=true&characterEncoding=utf8&useSSL=FALSE&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true    #  数据库连接地址
    username: root                             #  数据库用户名
    password: 123456                              #  数据库密码
    #    filters: stat,wall,log4j                      #  配置druid过滤器，开启监控
    dbcp2:                                        #  进行数据库连接池的配置
      min-idle: 5                                 #  数据库连接池的最小维持连接数
      initial-size: 5                             #  初始化提供的连接数
      max-total: 5                                #  最大连接数
      max-wait-millis: 200                        #  等待连接获取的最大超时时间
